# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42134ce8cdbb88b28d3a307f347de7fa48a615c29c9c178df400b77cdf30a305e6022173de6f9543a0706cb1eca79aca74e656da526edae330de1ecdf2197949

test:
  secret_key_base: 1d1145ac8a1231c0b4af9db54d3a866c86f049755e7f0d3331366554fce317efcdcbe60dc38aff163e5d88c5e22fb3c13fe48fb95fdbe1bc8b734deef158a39d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
